language: python
python:
  - '3.6'

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433

#  command to install dependences
install:
  - 'pip install -r requirements.txt'

services:
  - postgresql

before-script:
  - codeclimate-test-report before-build
  - psql -c 'create database tododb;' -U postgres
  - cp config/database.yml.travis config/database.yml

#  command to run tests
script:
  - nosetests --with-coverage --cover-tests
  - coverage report

after_success:
  - coveralls
