language: python
python:
  - '3.6'

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5432
    - PGPASSWORD="snOOkg"
    - PGHOST="localhost"
    - APP_ENV=testing
    - DATABASE_URL="postgresql+psycopg2://postgres:snOOkg@localhost:5432/tododb"
    - JWT_SECRET_KEY="mukungumayanja"

#  command to install dependences
install:
  - 'pip install -r requirements.txt'

services:
  - postgresql

before_script:
  #  - codeclimate-test-report before-build
  - psql -c "create database tododb;" -U postgres
  #  - psql -c "create user becks with password 'snOOkg';" -U postgres
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade

#  command to run tests
script:
  - nosetests --with-coverage --cover-tests
  - coverage report

after_success:
  - coveralls
